[package]
name = "docker_rs"
version = "0.1.0"
authors = ["Deepesh Pathak <deepshpathak@gmail.com>"]

[dependencies]
quick-error = "1.2.2"
serde_derive = "1.0.66"
serde = "1.0.66"
serde_json = "1.0.21"
